[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
test = "test"
cache_path = "cache"
solc_version = "0.8.25"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.alchemyapi.io/v2/${ALCHEMY_API_KEY}"

[fmt]
line_length = 100
tab_width = 4
use_tabs = false
bracket_spacing = false

[profile.test]
optimizer_runs = 200
via_ir = true
